#!/bin/bash -eux

apt_packages_list=(
    emacs
    emacs-mozc-bin
    tree
    xsel
    vim
    fonts-noto-color-emoji
    htop
    vlc
    libreoffice
    libvirt-clients
    libvirt-daemon
    virt-manager
    qemu-kvm
    jq
    fcitx5
    fcitx5-mozc
    mozc-utils-gui
    speedtest-cli
    pwgen
    glances
    python3-tqdm
    qterminal
    seahorse
    crudini
)

sudo DEBIAN_FRONTEND=noninteractive apt-get install -qq "${apt_packages_list[@]}"
