#!/bin/bash -eux

apt_packages_list=(
    emacs
    emacs-mozc-bin
    dconf-cli
    dconf-editor
    tree
    xsel
    vim
    fonts-noto-color-emoji
    htop
    vlc
    libreoffice
    libvirt-clients
    libvirt-daemon
    virt-manager
    qemu-kvm
    jq
    fcitx5
    fcitx5-mozc
    mozc-utils-gui
    speedtest-cli
    pwgen
    glances
    python3-tqdm
    qterminal
)

sudo apt-get install -qq "${apt_packages_list[@]}"

mkdir -p ~/.config/autostart

autostart_package=(guake.desktop emacs.desktop google-chrome.desktop)

for package in "${autostart_package[@]}"; do
    test -f /usr/share/applications/"${package}" && \
        ln -sf /usr/share/applications/"${package}" ~/.config/autostart/"${package}"
done
