#!/bin/bash -eux

[[ $(id -u) -eq 0 ]] || exec sudo -E "$0"

deb_dir=$(mktemp -d)

pushd "${deb_dir}" > /dev/null

curl -sLo google-chrome.deb "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
curl -sLo dropbox.deb "https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2022.12.05_amd64.deb"
curl -sLo vscode.deb "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"

apt-get install -qqf "${deb_dir}"/*.deb

popd > /dev/null
rm -fr "${deb_dir}"
