#!/bin/bash -eux

dotfiles_root_directory=$(git rev-parse --show-toplevel)

dotfiles_list=(
    .bashrc
    .profile
    .emacs.d/
    .gitconfig
    .gitignore_global
    .tmux.conf
    .tmux.conf.linux
    .tmux.conf.macos
    .vim/
    .bash_completion
    .bash_aliases
    .markdownlint.yaml
    .claude/settings.json
    .claude/statusline.py
)

for dotfile in "${dotfiles_list[@]}"; do
    mkdir -p "$(dirname "${HOME}/${dotfile%/}")"
    ln -sfn "${dotfiles_root_directory}/${dotfile}" "${HOME}/${dotfile%/}"
done
