#!/bin/bash -eux

cd "$(dirname "$0")"

while read -r ext; do
    code --install-extension "${ext}";
done < ~/.dotfiles/vscode/extensions.txt

ln -sf ~/.dotfiles/vscode/settings.json ~/.config/Code/User/settings.json
