version: 8
profiles: []
groups: []
configSync:
  parts: {}
hotkeys:
  toggle-window: []
  copy-current-path: []
  ctrl-c: []
  copy: []
  paste: []
  select-all: []
  clear: []
  zoom-in: []
  zoom-out: []
  reset-zoom: []
  home: []
  end: []
  previous-word: []
  next-word: []
  delete-previous-word: []
  delete-line: []
  delete-next-word: []
  search: []
  pane-focus-all: []
  focus-all-tabs: []
  scroll-to-top: []
  scroll-page-up: []
  scroll-up: []
  scroll-down: []
  scroll-page-down: []
  scroll-to-bottom: []
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  open-sftp: []
  settings-tab: {}
  settings: []
  serial: []
  restart-serial-session: []
  new-tab: []
  new-window: []
  profile: {}
  profile-selectors: {}
  group-selectors: {}
  toggle-fullscreen: []
  close-tab: []
  reopen-tab: []
  toggle-last-tab: []
  rename-tab: []
  next-tab: []
  previous-tab: []
  move-tab-left: []
  move-tab-right: []
  rearrange-panes: []
  duplicate-tab: []
  restart-tab: []
  reconnect-tab: []
  disconnect-tab: []
  explode-tab: []
  combine-tabs: []
  tab-1: []
  tab-2: []
  tab-3: []
  tab-4: []
  tab-5: []
  tab-6: []
  tab-7: []
  tab-8: []
  tab-9: []
  tab-10: []
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right: []
  split-bottom: []
  split-left: []
  split-top: []
  pane-nav-right: []
  pane-nav-down: []
  pane-nav-up: []
  pane-nav-left: []
  pane-nav-previous: []
  pane-nav-next: []
  pane-nav-1: []
  pane-nav-2: []
  pane-nav-3: []
  pane-nav-4: []
  pane-nav-5: []
  pane-nav-6: []
  pane-nav-7: []
  pane-nav-8: []
  pane-nav-9: []
  pane-maximize: []
  pane-increase-vertical: []
  pane-decrease-vertical: []
  pane-increase-horizontal: []
  pane-decrease-horizontal: []
  close-pane: []
  switch-profile: []
  profile-selector: []
  command-selector: []
terminal:
  searchOptions: {}
  colorScheme:
    name: Tango
    foreground: '#babdb6'
    background: '#000000'
    cursor: '#babdb6'
    colors:
      - '#2e3436'
      - '#cc0000'
      - '#4e9a06'
      - '#c4a000'
      - '#3465a4'
      - '#75507b'
      - '#06989a'
      - '#d3d7cf'
      - '#555753'
      - '#ef2929'
      - '#8ae234'
      - '#fce94f'
      - '#729fcf'
      - '#ad7fa8'
      - '#34e2e2'
      - '#eeeeec'
  font: Hack
  fontWeight: 500
  fontWeightBold: 500
  cursor: beam
  customColorSchemes: []
  lightColorScheme:
    name: Tabby Default Light
    foreground: '#4d4d4c'
    background: '#ffffff'
    cursor: '#4d4d4c'
    colors:
      - '#000000'
      - '#c82829'
      - '#718c00'
      - '#eab700'
      - '#4271ae'
      - '#8959a8'
      - '#3e999f'
      - '#ffffff'
      - '#000000'
      - '#c82829'
      - '#718c00'
      - '#eab700'
      - '#4271ae'
      - '#8959a8'
      - '#3e999f'
      - '#ffffff'
  fallbackFont: Noto Sans Mono CJK JP
  linePadding: 0.5
  hideTabIndex: true
  hideTabOptionsButton: true
  hideCloseButton: true
ssh: {}
clickableLinks: {}
accessibility: {}
appearance: {}
hacks: {}
providerBlacklist: []
commandBlacklist: []
profileDefaults:
  ssh:
    disableDynamicTitle: true
profileBlacklist: []
enableAnalytics: false
enableWelcomeTab: false
pluginBlacklist: []
