# https://github.com/DavidAnson/markdownlint/blob/v0.37.4/schema/.markdownlint.yaml

# MD013/line-length
MD013: false

# MD024/no-duplicate-heading
MD024: false

# MD033/no-inline-html
MD033:
  allowed_elements: ["details", "summary", "code", "div"]
