version: 2.1
commands:
  build:
    steps:
      - checkout
      - run: sudo apt-get update -yq
      - run: bootstrap/deb
      - run: bootstrap/misc
      - run: bootstrap/dconf
      - run: bootstrap/dotfiles_symlink
      - run: bootstrap/apt
      - run: bootstrap/docker
      - run: bootstrap/homebrew

executors:
  ubuntu-focal:
    docker:
      - image: maya2250/dotfiles:ubuntu-20.04

jobs:
  build:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    working_directory: ~/.dotfiles
    steps:
      - build

workflows:
  version: 2
  matrix-build:
    jobs:
      - build:
          name: ubuntu-focal
          executor: ubuntu-focal
