version: 2.1
commands:
  build:
    steps:
      - checkout
      - run: bootstrap/deb
      - run: bootstrap/misc
      - run: bootstrap/dconf
      - run: bootstrap/dotfiles_symlink
      - run: bootstrap/apt
      - run: bootstrap/docker
      - run: bootstrap/homebrew

jobs:
  build:
    docker:
      - image: maya2250/dotfiles:ubuntu-19.10
    working_directory: ~/.dotfiles
    steps:
      - run: sudo apt-get update -yq
      - build
