version: 2.1

jobs:
  build:
    docker:
      - image: maya2250/dotfiles:latest
    working_directory: ~/project
    steps:
      - checkout
      - run: sudo apt-get update -qq
      - run: ./install
      - run: ./install_brew
      - run: sudo -E ./ubuntu/install_deb_packages
      - run: sudo -E ./ubuntu/install_apt_packages
      - run: sudo -E ./ubuntu/install_powerline
      - run: sudo -E ./ubuntu/install_docker
      - run: ./ubuntu/install_font
