version: 2.1
commands:
  build:
    steps:
      - checkout
      - run: sudo apt-get update -yq
      - run: bootstrap/0_apt
      - run: bootstrap/deb
      - run: bootstrap/misc
      - run: bootstrap/dconf
      - run: bootstrap/dotfiles_symlink
      - run: bootstrap/docker
      - run:
          command: bootstrap/homebrew
          no_output_timeout: 30m

executors:
  ubuntu:
    docker:
      - image: maya2250/dotfiles:ubuntu-23.04

jobs:
  build:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    working_directory: ~/.dotfiles
    steps:
      - build

workflows:
  version: 2
  matrix-build:
    jobs:
      - build:
          name: ubuntu
          executor: ubuntu
